# Docker compose for netflix conductor + elasticsearch + dynomite
version: '2'

# Use docker-compose -p conductor when bringing these containers up

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
    image: conductor:server
    volumes:
      # override some config settings
      - ./config.properties.local:/app/config/config.properties
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - 8080:8080
    links:
      - elasticsearch:es
      - dynomite:dyno1

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor:ui
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    ports:
      - 5001:5000
    links:
      - conductor-server

  dynomite:
    image: v1r3n/dynomite
    logging:
      # limit logs to 200mb -- roughly 2 days!
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 9200:9200
